# Site settings
title: Julian Dawson
email: julian@juliandawson.co.uk
description: Articles on JavaScript, Angular, React and HTML5
baseurl: ""
url: ""
twitter_username: julianmdawson
github_username:  juliandawson
sass:
  compressed: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - tsconfig.json
  - tslint.json
  - node_modules

# Collections
collections:
  projects:
    output: true